#pragma once

//Screen dimensions
#define SCREEN_WIDTH 512
#define SCREEN_HEIGHT 416
#define MAP_HEIGHT 13
#define MAP_WIDTH 16
#define GRAVITY 96.0f
#define TILE_WIDTH 32
#define TILE_HEIGHT 32
#define SCREENSHAKE_DURATION 0.25f
#define JUMP_FORCE_DECREMENT 400.0f
#define INITIAL_JUMP_FORCE 400.0f
#define INITIAL_JUMP_FORCE_SMALL 200.0f
#define INJURED_TIME 2.5f
#define KOOPA_SPEED 40.0f
#define COIN_SPEED 1.5f